apiVersion: v1
kind: Service
metadata:
  name: premortem-agent-builder
  namespace: {{ .Values.global.namespace | quote }}
  labels:
{{ include "premortem.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: premortem-agent-builder
  ports:
    - name: http
      port: 8080
      targetPort: http
