apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
{{ include "premortem.labels" . | indent 4 }}
