import type { Prisma } from '@prisma/client';
import { type ReviewActionValue } from '@premortem/domain';
export declare function createAuditRun(input: {
    organizationId: string;
    projectId: string;
    branch: string;
    commitSha?: string;
    triggeredById?: string;
    triggerSource?: Prisma.AuditRunCreateInput['triggerSource'];
}): Promise<{
    projectId: string;
    branch: string;
    summary: Prisma.JsonValue;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    organizationId: string;
    commitSha: string | null;
    triggerSource: import("@prisma/client").$Enums.AuditTriggerSource;
    triggeredById: string | null;
    runStatus: import("@prisma/client").$Enums.RunStatus;
    startedAt: Date | null;
    completedAt: Date | null;
    leaseExpiresAt: Date | null;
    cancelledAt: Date | null;
    cancelReason: string | null;
    durationMs: bigint | null;
    graphSnapshotId: string | null;
    errorMessage: string | null;
}>;
export declare function markAuditRunning(auditRunId: string): Promise<{
    projectId: string;
    branch: string;
    summary: Prisma.JsonValue;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    organizationId: string;
    commitSha: string | null;
    triggerSource: import("@prisma/client").$Enums.AuditTriggerSource;
    triggeredById: string | null;
    runStatus: import("@prisma/client").$Enums.RunStatus;
    startedAt: Date | null;
    completedAt: Date | null;
    leaseExpiresAt: Date | null;
    cancelledAt: Date | null;
    cancelReason: string | null;
    durationMs: bigint | null;
    graphSnapshotId: string | null;
    errorMessage: string | null;
}>;
export declare function markAuditCompleted(auditRunId: string, summary: Prisma.JsonObject): Promise<{
    projectId: string;
    branch: string;
    summary: Prisma.JsonValue;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    organizationId: string;
    commitSha: string | null;
    triggerSource: import("@prisma/client").$Enums.AuditTriggerSource;
    triggeredById: string | null;
    runStatus: import("@prisma/client").$Enums.RunStatus;
    startedAt: Date | null;
    completedAt: Date | null;
    leaseExpiresAt: Date | null;
    cancelledAt: Date | null;
    cancelReason: string | null;
    durationMs: bigint | null;
    graphSnapshotId: string | null;
    errorMessage: string | null;
}>;
export declare function markAuditPaused(auditRunId: string, summary: Prisma.JsonObject): Promise<{
    projectId: string;
    branch: string;
    summary: Prisma.JsonValue;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    organizationId: string;
    commitSha: string | null;
    triggerSource: import("@prisma/client").$Enums.AuditTriggerSource;
    triggeredById: string | null;
    runStatus: import("@prisma/client").$Enums.RunStatus;
    startedAt: Date | null;
    completedAt: Date | null;
    leaseExpiresAt: Date | null;
    cancelledAt: Date | null;
    cancelReason: string | null;
    durationMs: bigint | null;
    graphSnapshotId: string | null;
    errorMessage: string | null;
}>;
export declare function markAuditFailed(auditRunId: string, errorMessage: string): Promise<{
    projectId: string;
    branch: string;
    summary: Prisma.JsonValue;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    organizationId: string;
    commitSha: string | null;
    triggerSource: import("@prisma/client").$Enums.AuditTriggerSource;
    triggeredById: string | null;
    runStatus: import("@prisma/client").$Enums.RunStatus;
    startedAt: Date | null;
    completedAt: Date | null;
    leaseExpiresAt: Date | null;
    cancelledAt: Date | null;
    cancelReason: string | null;
    durationMs: bigint | null;
    graphSnapshotId: string | null;
    errorMessage: string | null;
}>;
export declare function createAuditRunEvent(input: {
    auditRunId: string;
    eventType: string;
    actor?: string;
    payload?: Record<string, unknown>;
}): Promise<{
    id: string;
    createdAt: Date;
    auditRunId: string;
    eventType: string;
    actor: string;
    payload: Prisma.JsonValue;
}>;
export declare function createAgentRun(input: {
    auditRunId: string;
    agentName: string;
    runMode: 'always' | 'conditional';
}): Promise<{
    status: import("@prisma/client").$Enums.RunStatus;
    id: string;
    createdAt: Date;
    auditRunId: string;
    startedAt: Date | null;
    completedAt: Date | null;
    durationMs: bigint | null;
    errorMessage: string | null;
    agentName: string;
    runMode: import("@prisma/client").$Enums.AgentRunMode;
    skippedReason: string | null;
    inputDigest: string | null;
    outputDigest: string | null;
    promptVersion: string | null;
    modelRef: string | null;
    tokenUsage: Prisma.JsonValue;
    rawOutput: Prisma.JsonValue | null;
}>;
export declare function completeAgentRun(agentRunId: string, payload?: Prisma.JsonObject): Promise<{
    status: import("@prisma/client").$Enums.RunStatus;
    id: string;
    createdAt: Date;
    auditRunId: string;
    startedAt: Date | null;
    completedAt: Date | null;
    durationMs: bigint | null;
    errorMessage: string | null;
    agentName: string;
    runMode: import("@prisma/client").$Enums.AgentRunMode;
    skippedReason: string | null;
    inputDigest: string | null;
    outputDigest: string | null;
    promptVersion: string | null;
    modelRef: string | null;
    tokenUsage: Prisma.JsonValue;
    rawOutput: Prisma.JsonValue | null;
}>;
export declare function failAgentRun(agentRunId: string, errorMessage: string): Promise<{
    status: import("@prisma/client").$Enums.RunStatus;
    id: string;
    createdAt: Date;
    auditRunId: string;
    startedAt: Date | null;
    completedAt: Date | null;
    durationMs: bigint | null;
    errorMessage: string | null;
    agentName: string;
    runMode: import("@prisma/client").$Enums.AgentRunMode;
    skippedReason: string | null;
    inputDigest: string | null;
    outputDigest: string | null;
    promptVersion: string | null;
    modelRef: string | null;
    tokenUsage: Prisma.JsonValue;
    rawOutput: Prisma.JsonValue | null;
}>;
export declare function persistFindings(input: {
    organizationId: string;
    projectId: string;
    auditRunId: string;
    agentRunId: string;
    findings: Array<{
        findingKey: string;
        category: string;
        findingType: string;
        severity: 'low' | 'medium' | 'high' | 'critical';
        confidence: number;
        predictedFailureSummary: string;
        failureMode?: string;
        whyItMatters?: string;
        blastRadius?: string;
        triggerConditions: string[];
        affectedAssets: string[];
        evidence: unknown[];
        recommendedControls: string[];
        dedupeKeys: string[];
        tags: string[];
    }>;
}): Promise<{
    projectId: string;
    category: string;
    status: import("@prisma/client").$Enums.FindingStatus;
    severity: import("@prisma/client").$Enums.SeverityLevel;
    confidence: Prisma.Decimal;
    evidence: Prisma.JsonValue;
    tags: Prisma.JsonValue;
    whyItMatters: string | null;
    predictedFailureSummary: string;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    auditRunId: string;
    organizationId: string;
    agentRunId: string;
    findingKey: string;
    findingType: string;
    priorityHint: import("@prisma/client").$Enums.PriorityLevel;
    blastRadius: string | null;
    failureMode: string | null;
    triggerConditions: Prisma.JsonValue;
    affectedAssets: Prisma.JsonValue;
    recommendedControls: Prisma.JsonValue;
    dedupeKeys: Prisma.JsonValue;
}[]>;
export declare function createDedupeClusters(input: {
    organizationId: string;
    projectId: string;
    auditRunId: string;
    clusters: Array<{
        clusterKey: string;
        categoryOwner: string;
        titleHint?: string;
        severity: 'low' | 'medium' | 'high' | 'critical';
        confidence: number;
        blastRadius?: string;
        assetScope: string[];
        triggerSignature: string[];
        findings: Array<{
            findingId: string;
            role?: string;
            similarityScore?: number;
        }>;
    }>;
}): Promise<({
    members: {
        id: string;
        role: string;
        createdAt: Date;
        similarityScore: Prisma.Decimal;
        findingId: string;
        clusterId: string;
    }[];
} & {
    projectId: string;
    severity: import("@prisma/client").$Enums.SeverityLevel;
    confidence: Prisma.Decimal;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    auditRunId: string;
    organizationId: string;
    blastRadius: string | null;
    clusterKey: string;
    categoryOwner: string;
    titleHint: string | null;
    mergeStatus: import("@prisma/client").$Enums.ClusterMergeStatus;
    assetScope: Prisma.JsonValue;
    triggerSignature: Prisma.JsonValue;
})[]>;
export declare function persistIssueCandidates(input: {
    organizationId: string;
    projectId: string;
    auditRunId: string;
    issues: Array<{
        clusterId: string;
        title: string;
        category: string;
        severity: 'low' | 'medium' | 'high' | 'critical';
        confidence: number;
        predictedFailureSummary: string;
        whyItMatters: string;
        triggerConditions: string[];
        evidence: unknown[];
        recommendedActionSummary: string;
        implementationSteps: string[];
        doneCriteria: string[];
        affectedAssets: string[];
        sourceAgents: string[];
        sourceFindings: string[];
        validationStatus: 'passed' | 'failed';
        validationErrors: string[];
        validationWarnings: string[];
        validatorName: string;
    }>;
}): Promise<({
    versions: {
        id: string;
        createdAt: Date;
        versionNo: number;
        bodySnapshot: Prisma.JsonValue;
        editReason: string | null;
        editedById: string | null;
        issueCandidateId: string;
    }[];
    validationResults: {
        status: import("@prisma/client").$Enums.ValidationStatus;
        id: string;
        createdAt: Date;
        validatorName: string;
        errors: Prisma.JsonValue;
        warnings: Prisma.JsonValue;
        score: Prisma.Decimal | null;
        issueCandidateId: string;
    }[];
} & {
    projectId: string;
    category: string;
    severity: import("@prisma/client").$Enums.SeverityLevel;
    confidence: Prisma.Decimal;
    evidence: Prisma.JsonValue;
    title: string;
    whyItMatters: string;
    recommendedActionSummary: string;
    predictedFailureSummary: string;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    priority: import("@prisma/client").$Enums.PriorityLevel;
    auditRunId: string;
    organizationId: string;
    blastRadius: string | null;
    failureMode: string | null;
    triggerConditions: Prisma.JsonValue;
    affectedAssets: Prisma.JsonValue;
    clusterId: string;
    implementationSteps: Prisma.JsonValue;
    doneCriteria: Prisma.JsonValue;
    sourceAgents: Prisma.JsonValue;
    sourceFindings: Prisma.JsonValue;
    validationStatus: import("@prisma/client").$Enums.ValidationStatus;
    validationErrors: Prisma.JsonValue;
    reviewerStatus: import("@prisma/client").$Enums.ReviewStatus;
    reviewerNotes: string | null;
    approvedById: string | null;
    approvedAt: Date | null;
})[]>;
export declare function persistRejectedIssueCandidateArtifacts(input: {
    organizationId: string;
    projectId: string;
    auditRunId: string;
    issues: Array<{
        clusterId?: string;
        title: string;
        category: string;
        severity: 'low' | 'medium' | 'high' | 'critical';
        confidence: number;
        predictedFailureSummary: string;
        whyItMatters: string;
        triggerConditions: string[];
        evidence: unknown[];
        recommendedActionSummary: string;
        implementationSteps: string[];
        doneCriteria: string[];
        affectedAssets: string[];
        sourceAgents: string[];
        sourceFindings: string[];
        validationErrors: string[];
        validationWarnings: string[];
        validatorName: string;
    }>;
}): Promise<{
    projectId: string;
    category: string;
    severity: import("@prisma/client").$Enums.SeverityLevel;
    confidence: Prisma.Decimal;
    evidence: Prisma.JsonValue;
    title: string;
    whyItMatters: string;
    recommendedActionSummary: string;
    predictedFailureSummary: string;
    id: string;
    createdAt: Date;
    auditRunId: string;
    organizationId: string;
    triggerConditions: Prisma.JsonValue;
    affectedAssets: Prisma.JsonValue;
    clusterId: string | null;
    implementationSteps: Prisma.JsonValue;
    doneCriteria: Prisma.JsonValue;
    sourceAgents: Prisma.JsonValue;
    sourceFindings: Prisma.JsonValue;
    validationErrors: Prisma.JsonValue;
    validatorName: string;
    validationWarnings: Prisma.JsonValue;
}[]>;
export declare function getAuditRunDetails(auditRunId: string): Promise<({
    findings: {
        projectId: string;
        category: string;
        status: import("@prisma/client").$Enums.FindingStatus;
        severity: import("@prisma/client").$Enums.SeverityLevel;
        confidence: Prisma.Decimal;
        evidence: Prisma.JsonValue;
        tags: Prisma.JsonValue;
        whyItMatters: string | null;
        predictedFailureSummary: string;
        updatedAt: Date;
        id: string;
        createdAt: Date;
        auditRunId: string;
        organizationId: string;
        agentRunId: string;
        findingKey: string;
        findingType: string;
        priorityHint: import("@prisma/client").$Enums.PriorityLevel;
        blastRadius: string | null;
        failureMode: string | null;
        triggerConditions: Prisma.JsonValue;
        affectedAssets: Prisma.JsonValue;
        recommendedControls: Prisma.JsonValue;
        dedupeKeys: Prisma.JsonValue;
    }[];
    graphSnapshot: {
        projectId: string;
        id: string;
        createdAt: Date;
        auditRunId: string;
        organizationId: string;
        metadata: Prisma.JsonValue;
        graphVersion: string | null;
        nodeCount: number;
        edgeCount: number;
        storageRef: string | null;
    } | null;
    dedupeClusters: ({
        members: {
            id: string;
            role: string;
            createdAt: Date;
            similarityScore: Prisma.Decimal;
            findingId: string;
            clusterId: string;
        }[];
    } & {
        projectId: string;
        severity: import("@prisma/client").$Enums.SeverityLevel;
        confidence: Prisma.Decimal;
        updatedAt: Date;
        id: string;
        createdAt: Date;
        auditRunId: string;
        organizationId: string;
        blastRadius: string | null;
        clusterKey: string;
        categoryOwner: string;
        titleHint: string | null;
        mergeStatus: import("@prisma/client").$Enums.ClusterMergeStatus;
        assetScope: Prisma.JsonValue;
        triggerSignature: Prisma.JsonValue;
    })[];
    issueCandidates: ({
        publishedIssue: {
            projectId: string;
            labels: Prisma.JsonValue;
            updatedAt: Date;
            id: string;
            createdAt: Date;
            url: string | null;
            organizationId: string;
            provider: import("@prisma/client").$Enums.ProviderKind;
            lastSyncedAt: Date | null;
            issueCandidateId: string;
            externalIssueId: string | null;
            externalIssueIid: string | null;
            syncStatus: import("@prisma/client").$Enums.PublishSyncStatus;
            publishedTitle: string;
            publishedBodyMd: string;
            publishedAt: Date | null;
            closedAt: Date | null;
            outcomeType: string | null;
            outcomeNotes: string | null;
            outcomeAt: Date | null;
        } | null;
        versions: {
            id: string;
            createdAt: Date;
            versionNo: number;
            bodySnapshot: Prisma.JsonValue;
            editReason: string | null;
            editedById: string | null;
            issueCandidateId: string;
        }[];
        validationResults: {
            status: import("@prisma/client").$Enums.ValidationStatus;
            id: string;
            createdAt: Date;
            validatorName: string;
            errors: Prisma.JsonValue;
            warnings: Prisma.JsonValue;
            score: Prisma.Decimal | null;
            issueCandidateId: string;
        }[];
    } & {
        projectId: string;
        category: string;
        severity: import("@prisma/client").$Enums.SeverityLevel;
        confidence: Prisma.Decimal;
        evidence: Prisma.JsonValue;
        title: string;
        whyItMatters: string;
        recommendedActionSummary: string;
        predictedFailureSummary: string;
        updatedAt: Date;
        id: string;
        createdAt: Date;
        priority: import("@prisma/client").$Enums.PriorityLevel;
        auditRunId: string;
        organizationId: string;
        blastRadius: string | null;
        failureMode: string | null;
        triggerConditions: Prisma.JsonValue;
        affectedAssets: Prisma.JsonValue;
        clusterId: string;
        implementationSteps: Prisma.JsonValue;
        doneCriteria: Prisma.JsonValue;
        sourceAgents: Prisma.JsonValue;
        sourceFindings: Prisma.JsonValue;
        validationStatus: import("@prisma/client").$Enums.ValidationStatus;
        validationErrors: Prisma.JsonValue;
        reviewerStatus: import("@prisma/client").$Enums.ReviewStatus;
        reviewerNotes: string | null;
        approvedById: string | null;
        approvedAt: Date | null;
    })[];
    rejectedIssueCandidateArtifacts: {
        projectId: string;
        category: string;
        severity: import("@prisma/client").$Enums.SeverityLevel;
        confidence: Prisma.Decimal;
        evidence: Prisma.JsonValue;
        title: string;
        whyItMatters: string;
        recommendedActionSummary: string;
        predictedFailureSummary: string;
        id: string;
        createdAt: Date;
        auditRunId: string;
        organizationId: string;
        triggerConditions: Prisma.JsonValue;
        affectedAssets: Prisma.JsonValue;
        clusterId: string | null;
        implementationSteps: Prisma.JsonValue;
        doneCriteria: Prisma.JsonValue;
        sourceAgents: Prisma.JsonValue;
        sourceFindings: Prisma.JsonValue;
        validationErrors: Prisma.JsonValue;
        validatorName: string;
        validationWarnings: Prisma.JsonValue;
    }[];
    agentRuns: {
        status: import("@prisma/client").$Enums.RunStatus;
        id: string;
        createdAt: Date;
        auditRunId: string;
        startedAt: Date | null;
        completedAt: Date | null;
        durationMs: bigint | null;
        errorMessage: string | null;
        agentName: string;
        runMode: import("@prisma/client").$Enums.AgentRunMode;
        skippedReason: string | null;
        inputDigest: string | null;
        outputDigest: string | null;
        promptVersion: string | null;
        modelRef: string | null;
        tokenUsage: Prisma.JsonValue;
        rawOutput: Prisma.JsonValue | null;
    }[];
    events: {
        id: string;
        createdAt: Date;
        auditRunId: string;
        eventType: string;
        actor: string;
        payload: Prisma.JsonValue;
    }[];
} & {
    projectId: string;
    branch: string;
    summary: Prisma.JsonValue;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    organizationId: string;
    commitSha: string | null;
    triggerSource: import("@prisma/client").$Enums.AuditTriggerSource;
    triggeredById: string | null;
    runStatus: import("@prisma/client").$Enums.RunStatus;
    startedAt: Date | null;
    completedAt: Date | null;
    leaseExpiresAt: Date | null;
    cancelledAt: Date | null;
    cancelReason: string | null;
    durationMs: bigint | null;
    graphSnapshotId: string | null;
    errorMessage: string | null;
}) | null>;
export declare function persistGraphSnapshot(input: {
    organizationId: string;
    projectId: string;
    auditRunId: string;
    nodeCount: number;
    edgeCount: number;
    metadata?: Record<string, unknown>;
    storageRef?: string;
}): Promise<{
    projectId: string;
    id: string;
    createdAt: Date;
    auditRunId: string;
    organizationId: string;
    metadata: Prisma.JsonValue;
    graphVersion: string | null;
    nodeCount: number;
    edgeCount: number;
    storageRef: string | null;
}>;
export declare function listOrganizationProjects(organizationId: string): Promise<({
    projectSettings: {
        projectId: string;
        updatedAt: Date;
        createdAt: Date;
        autoRunOnPush: boolean;
        autoPublishApprovedIssues: boolean;
        auditDefaultBranchOnly: boolean;
        enabledAgents: Prisma.JsonValue;
        severityThreshold: import("@prisma/client").$Enums.SeverityLevel;
        labelsTemplate: Prisma.JsonValue;
        ignorePaths: Prisma.JsonValue;
        notificationSettings: Prisma.JsonValue;
    } | null;
} & {
    status: import("@prisma/client").$Enums.ProjectStatus;
    updatedAt: Date;
    id: string;
    name: string;
    createdAt: Date;
    connectionId: string | null;
    organizationId: string;
    provider: import("@prisma/client").$Enums.ProviderKind;
    createdById: string | null;
    slug: string;
    metadata: Prisma.JsonValue;
    externalProjectId: string;
    namespace: string | null;
    repoUrl: string | null;
    defaultBranch: string | null;
    visibility: string | null;
    settings: Prisma.JsonValue;
    connectedAt: Date | null;
})[]>;
export declare function slugifyProjectNameForRepo(name: string): string;
export declare function createOrganizationProject(input: {
    organizationId: string;
    name: string;
    provider: 'gitlab' | 'github';
    repoUrl?: string;
    defaultBranch?: string;
    createdById?: string;
    scanCodeSnippet?: string;
}): Promise<{
    projectSettings: {
        projectId: string;
        updatedAt: Date;
        createdAt: Date;
        autoRunOnPush: boolean;
        autoPublishApprovedIssues: boolean;
        auditDefaultBranchOnly: boolean;
        enabledAgents: Prisma.JsonValue;
        severityThreshold: import("@prisma/client").$Enums.SeverityLevel;
        labelsTemplate: Prisma.JsonValue;
        ignorePaths: Prisma.JsonValue;
        notificationSettings: Prisma.JsonValue;
    } | null;
    status: import("@prisma/client").$Enums.ProjectStatus;
    updatedAt: Date;
    id: string;
    name: string;
    createdAt: Date;
    connectionId: string | null;
    organizationId: string;
    provider: import("@prisma/client").$Enums.ProviderKind;
    createdById: string | null;
    slug: string;
    metadata: Prisma.JsonValue;
    externalProjectId: string;
    namespace: string | null;
    repoUrl: string | null;
    defaultBranch: string | null;
    visibility: string | null;
    settings: Prisma.JsonValue;
    connectedAt: Date | null;
}>;
export declare function updateProjectSettings(input: {
    organizationId: string;
    projectId: string;
    autoRunOnPush?: boolean;
    autoPublishApprovedIssues?: boolean;
    auditDefaultBranchOnly?: boolean;
    enabledAgents?: string[];
    severityThreshold?: 'low' | 'medium' | 'high' | 'critical';
    labelsTemplate?: string[];
    ignorePaths?: string[];
    notificationSettings?: Record<string, unknown>;
}): Promise<{
    projectId: string;
    updatedAt: Date;
    createdAt: Date;
    autoRunOnPush: boolean;
    autoPublishApprovedIssues: boolean;
    auditDefaultBranchOnly: boolean;
    enabledAgents: Prisma.JsonValue;
    severityThreshold: import("@prisma/client").$Enums.SeverityLevel;
    labelsTemplate: Prisma.JsonValue;
    ignorePaths: Prisma.JsonValue;
    notificationSettings: Prisma.JsonValue;
}>;
export declare function getIssueCandidateDetails(issueCandidateId: string): Promise<({
    project: {
        status: import("@prisma/client").$Enums.ProjectStatus;
        updatedAt: Date;
        id: string;
        name: string;
        createdAt: Date;
        connectionId: string | null;
        organizationId: string;
        provider: import("@prisma/client").$Enums.ProviderKind;
        createdById: string | null;
        slug: string;
        metadata: Prisma.JsonValue;
        externalProjectId: string;
        namespace: string | null;
        repoUrl: string | null;
        defaultBranch: string | null;
        visibility: string | null;
        settings: Prisma.JsonValue;
        connectedAt: Date | null;
    };
    publishedIssue: {
        projectId: string;
        labels: Prisma.JsonValue;
        updatedAt: Date;
        id: string;
        createdAt: Date;
        url: string | null;
        organizationId: string;
        provider: import("@prisma/client").$Enums.ProviderKind;
        lastSyncedAt: Date | null;
        issueCandidateId: string;
        externalIssueId: string | null;
        externalIssueIid: string | null;
        syncStatus: import("@prisma/client").$Enums.PublishSyncStatus;
        publishedTitle: string;
        publishedBodyMd: string;
        publishedAt: Date | null;
        closedAt: Date | null;
        outcomeType: string | null;
        outcomeNotes: string | null;
        outcomeAt: Date | null;
    } | null;
    cluster: {
        projectId: string;
        severity: import("@prisma/client").$Enums.SeverityLevel;
        confidence: Prisma.Decimal;
        updatedAt: Date;
        id: string;
        createdAt: Date;
        auditRunId: string;
        organizationId: string;
        blastRadius: string | null;
        clusterKey: string;
        categoryOwner: string;
        titleHint: string | null;
        mergeStatus: import("@prisma/client").$Enums.ClusterMergeStatus;
        assetScope: Prisma.JsonValue;
        triggerSignature: Prisma.JsonValue;
    };
    versions: {
        id: string;
        createdAt: Date;
        versionNo: number;
        bodySnapshot: Prisma.JsonValue;
        editReason: string | null;
        editedById: string | null;
        issueCandidateId: string;
    }[];
    reviewActions: {
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue;
        issueCandidateId: string;
        actionType: import("@prisma/client").$Enums.ReviewActionType;
        notes: string | null;
        actorId: string;
    }[];
} & {
    projectId: string;
    category: string;
    severity: import("@prisma/client").$Enums.SeverityLevel;
    confidence: Prisma.Decimal;
    evidence: Prisma.JsonValue;
    title: string;
    whyItMatters: string;
    recommendedActionSummary: string;
    predictedFailureSummary: string;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    priority: import("@prisma/client").$Enums.PriorityLevel;
    auditRunId: string;
    organizationId: string;
    blastRadius: string | null;
    failureMode: string | null;
    triggerConditions: Prisma.JsonValue;
    affectedAssets: Prisma.JsonValue;
    clusterId: string;
    implementationSteps: Prisma.JsonValue;
    doneCriteria: Prisma.JsonValue;
    sourceAgents: Prisma.JsonValue;
    sourceFindings: Prisma.JsonValue;
    validationStatus: import("@prisma/client").$Enums.ValidationStatus;
    validationErrors: Prisma.JsonValue;
    reviewerStatus: import("@prisma/client").$Enums.ReviewStatus;
    reviewerNotes: string | null;
    approvedById: string | null;
    approvedAt: Date | null;
}) | null>;
export declare class PublishNotApprovedError extends Error {
    readonly code = "publish_not_approved";
    readonly field = "reviewerStatus";
    readonly status = 422;
    constructor();
}
export declare function assertIssueCandidateApprovedForPublish(issueCandidateId: string): Promise<void>;
export declare function splitIssueCandidate(input: {
    issueCandidateId: string;
    actorId: string;
    title: string;
    notes?: string;
}): Promise<{
    parent: {
        cluster: {
            members: {
                id: string;
                role: string;
                createdAt: Date;
                similarityScore: Prisma.Decimal;
                findingId: string;
                clusterId: string;
            }[];
        } & {
            projectId: string;
            severity: import("@prisma/client").$Enums.SeverityLevel;
            confidence: Prisma.Decimal;
            updatedAt: Date;
            id: string;
            createdAt: Date;
            auditRunId: string;
            organizationId: string;
            blastRadius: string | null;
            clusterKey: string;
            categoryOwner: string;
            titleHint: string | null;
            mergeStatus: import("@prisma/client").$Enums.ClusterMergeStatus;
            assetScope: Prisma.JsonValue;
            triggerSignature: Prisma.JsonValue;
        };
    } & {
        projectId: string;
        category: string;
        severity: import("@prisma/client").$Enums.SeverityLevel;
        confidence: Prisma.Decimal;
        evidence: Prisma.JsonValue;
        title: string;
        whyItMatters: string;
        recommendedActionSummary: string;
        predictedFailureSummary: string;
        updatedAt: Date;
        id: string;
        createdAt: Date;
        priority: import("@prisma/client").$Enums.PriorityLevel;
        auditRunId: string;
        organizationId: string;
        blastRadius: string | null;
        failureMode: string | null;
        triggerConditions: Prisma.JsonValue;
        affectedAssets: Prisma.JsonValue;
        clusterId: string;
        implementationSteps: Prisma.JsonValue;
        doneCriteria: Prisma.JsonValue;
        sourceAgents: Prisma.JsonValue;
        sourceFindings: Prisma.JsonValue;
        validationStatus: import("@prisma/client").$Enums.ValidationStatus;
        validationErrors: Prisma.JsonValue;
        reviewerStatus: import("@prisma/client").$Enums.ReviewStatus;
        reviewerNotes: string | null;
        approvedById: string | null;
        approvedAt: Date | null;
    };
    child: {
        projectId: string;
        category: string;
        severity: import("@prisma/client").$Enums.SeverityLevel;
        confidence: Prisma.Decimal;
        evidence: Prisma.JsonValue;
        title: string;
        whyItMatters: string;
        recommendedActionSummary: string;
        predictedFailureSummary: string;
        updatedAt: Date;
        id: string;
        createdAt: Date;
        priority: import("@prisma/client").$Enums.PriorityLevel;
        auditRunId: string;
        organizationId: string;
        blastRadius: string | null;
        failureMode: string | null;
        triggerConditions: Prisma.JsonValue;
        affectedAssets: Prisma.JsonValue;
        clusterId: string;
        implementationSteps: Prisma.JsonValue;
        doneCriteria: Prisma.JsonValue;
        sourceAgents: Prisma.JsonValue;
        sourceFindings: Prisma.JsonValue;
        validationStatus: import("@prisma/client").$Enums.ValidationStatus;
        validationErrors: Prisma.JsonValue;
        reviewerStatus: import("@prisma/client").$Enums.ReviewStatus;
        reviewerNotes: string | null;
        approvedById: string | null;
        approvedAt: Date | null;
    };
    action: {
        id: string;
        createdAt: Date;
        payload: Prisma.JsonValue;
        issueCandidateId: string;
        actionType: import("@prisma/client").$Enums.ReviewActionType;
        notes: string | null;
        actorId: string;
    };
}>;
export declare function recordReviewAction(input: {
    issueCandidateId: string;
    actorId: string;
    actionType: ReviewActionValue;
    notes?: string;
    payload?: Record<string, unknown>;
}): Promise<{
    id: string;
    createdAt: Date;
    payload: Prisma.JsonValue;
    issueCandidateId: string;
    actionType: import("@prisma/client").$Enums.ReviewActionType;
    notes: string | null;
    actorId: string;
}>;
export declare function listRecentAuditRuns(limit?: number): Promise<({
    issueCandidates: {
        id: string;
        validationStatus: import("@prisma/client").$Enums.ValidationStatus;
        reviewerStatus: import("@prisma/client").$Enums.ReviewStatus;
    }[];
    rejectedIssueCandidateArtifacts: {
        id: string;
    }[];
    events: {
        createdAt: Date;
        eventType: string;
    }[];
} & {
    projectId: string;
    branch: string;
    summary: Prisma.JsonValue;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    organizationId: string;
    commitSha: string | null;
    triggerSource: import("@prisma/client").$Enums.AuditTriggerSource;
    triggeredById: string | null;
    runStatus: import("@prisma/client").$Enums.RunStatus;
    startedAt: Date | null;
    completedAt: Date | null;
    leaseExpiresAt: Date | null;
    cancelledAt: Date | null;
    cancelReason: string | null;
    durationMs: bigint | null;
    graphSnapshotId: string | null;
    errorMessage: string | null;
})[]>;
export declare function listRecentAuditRunsForOrganization(organizationId: string, limit?: number): Promise<({
    issueCandidates: {
        id: string;
        validationStatus: import("@prisma/client").$Enums.ValidationStatus;
        reviewerStatus: import("@prisma/client").$Enums.ReviewStatus;
    }[];
    rejectedIssueCandidateArtifacts: {
        id: string;
    }[];
    events: {
        createdAt: Date;
        eventType: string;
    }[];
} & {
    projectId: string;
    branch: string;
    summary: Prisma.JsonValue;
    updatedAt: Date;
    id: string;
    createdAt: Date;
    organizationId: string;
    commitSha: string | null;
    triggerSource: import("@prisma/client").$Enums.AuditTriggerSource;
    triggeredById: string | null;
    runStatus: import("@prisma/client").$Enums.RunStatus;
    startedAt: Date | null;
    completedAt: Date | null;
    leaseExpiresAt: Date | null;
    cancelledAt: Date | null;
    cancelReason: string | null;
    durationMs: bigint | null;
    graphSnapshotId: string | null;
    errorMessage: string | null;
})[]>;
//# sourceMappingURL=repositories.d.ts.map