export const marketingLinks = {
  home: '/',
  products: '/products',
  solutions: '/solutions',
  howItWorks: '/how-it-works',
  privacy: '/privacy',
  terms: '/terms',
  docs: '/docs',
  docsGettingStarted: '/docs/getting-started',
  docsTutorialFirstAudit: '/docs/tutorials/first-audit',
  docsGuidesConnectGitlab: '/docs/guides/connect-gitlab',
  docsGuidesRunAudit: '/docs/guides/run-audit',
  docsGuidesReviewPublish: '/docs/guides/review-and-publish',
  docsGuidesDeployProduction: '/docs/guides/deploy-production',
  docsGuidesWorkflowCanvas: '/docs/guides/workflow-canvas',
  docsGuidesAuditHistory: '/docs/guides/audit-history',
  docsGuidesAiPlayground: '/docs/guides/ai-playground',
  docsGuidesWorkspaceSettings: '/docs/guides/workspace-settings',
  docsGuidesAuthSessions: '/docs/guides/auth-sessions',
  docsTutorialPublishGitlab: '/docs/tutorials/publish-gitlab-issue',
  docsReferenceApi: '/docs/reference/api',
  docsReferenceEnvironment: '/docs/reference/environment',
  docsReferenceBilling: '/docs/reference/billing-plans',
  docsReferenceNeo4j: '/docs/reference/neo4j-graph',
  docsReferenceObservability: '/docs/reference/observability',
  docsConceptsSecurity: '/docs/concepts/security',
  docsConceptsAuditModel: '/docs/concepts/audit-model',
  docsConceptsDataFlow: '/docs/concepts/data-flow',
  docsProductFlows: '/docs/product/flows',
  docsArchitecture: '/docs/architecture',
  docsIntegrationsGitlab: '/docs/integrations/gitlab',
  docsTroubleshooting: '/docs/troubleshooting',
  docsFaq: '/docs/faq',
  docsReleases: '/docs/releases',
  signup: '/signup',
  login: '/login',
  app: '/app',
  documentation: '/docs',
  documentationReadme: 'https://github.com/JustineDevs/premortem#readme',
  releases:
    'https://github.com/JustineDevs/premortem/blob/main/docs/releases/releases-notes-v0.1.0.md',
  license: 'https://github.com/JustineDevs/premortem/blob/main/LICENSE',
  maintainer: 'https://jstn.site',
  contactEmail: 'mailto:justinedevs@jstn.site',
  social: {
    github: 'https://github.com/justinedevs',
    linkedin: 'https://www.linkedin.com/in/justine-lupasi-444608295/',
    x: 'https://x.com/trader2g'
  }
} as const;
